name: cs7643_project
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.6.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - expat=2.6.3
  - libcxx=19.1.3
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgfortran   #=5.0.0
  - libgfortran5  #=11.3.0
  - libopenblas=0.3.21
  - libsqlite=3.47.0
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - ncurses=6.5
  - numpy=2.1.1
  - numpy-base=2.1.1
  - openssl=3.3.2
  - pandas=2.2.3
  - pip=24.2
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pydantic-settings=2.6.0
  - python=3.12.7
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - readline=8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.47.0
  - tk=8.6.13
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.3.1
