name: cs7643_project
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.6.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - expat=2.6.3
  - filelock=3.13.1
  - fsspec=2024.6.1
  - huggingface_hub=0.24.6
  - idna=3.7
  - jinja2=3.1.4
  - joblib=1.4.2
  - libabseil=20240116.2
  - libcxx=19.1.3
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libprotobuf=4.25.3
  - libsqlite=3.47.0
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markupsafe=2.1.3
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.3
  - pip=24.2
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pydantic-settings=2.6.0
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytorch=2.3.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - setuptools=72.1.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.47.0
  - sympy=1.13.2
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.20.1
  - tqdm=4.66.5
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.3.1
